### ISSUE TITLE
SC5P-PE and SC5P-R2

### ISSUE THREAD

**Issue by p4rkerw** [chung-lab/SCAFE#10]
Thanks for the great tool. I have 10 SC5P libraries where 4 were sequenced with SC5P-PE and 6 were sequenced with SC5P-R2. If I run the standard workflow on the SC5P-PE libraries and pool the results to identify the location of tCRE can I then use those locations to count and analyze the SC5P-R2 samples (even though they do not contain the TSO-DNA junction)? Similarly, could you use the tCRE locations from SC5P-PE samples to analyze a SC3P sample (even though it may have less sensitivity)?

**Comment by chung-lab** [comment]
Theoretically possible, but to count SC5' R2, you'll have to define customs ranges instead of using tCREs ranges. Typically the SC5' R2 should be couple of hundreds bp downstream of SC5' R1. For SC3' reads, the distance to TSS could be quite variable. This is similar to some colleagues using FANTOM CAGE defined eRNA loci to count RNASeq signal, for example in this paper (https://www.nature.com/articles/s41467-019-12543-5) they used +/-3kb to count RNASeq read.

To do that you would have to supply a custom bed file to the count script in SCAFE.
